-- MySQL Script generated by MySQL Workbench
-- Fri Feb 19 11:06:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clasificarIncident`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clasificarIncident` (
  `id` INT NOT NULL,
  `tipus_accident` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`incidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`incidencia` (
  `id` INT NOT NULL,
  `adreca` VARCHAR(100) NULL,
  `numero` VARCHAR(45) NULL,
  `descripcio` VARCHAR(200) NULL,
  `clasificarIncident_id` INT NOT NULL,
  PRIMARY KEY (`id`, `clasificarIncident_id`),
  INDEX `fk_incidencia_clasificarIncident1_idx` (`clasificarIncident_id` ASC) VISIBLE,
  CONSTRAINT `fk_incidencia_clasificarIncident1`
    FOREIGN KEY (`clasificarIncident_id`)
    REFERENCES `mydb`.`clasificarIncident` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trucada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trucada` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(20) NULL,
  `data` DATETIME NULL,
  `incidencia_id` INT NOT NULL,
  PRIMARY KEY (`id`, `incidencia_id`),
  INDEX `fk_trucada_incidencia1_idx` (`incidencia_id` ASC) VISIBLE,
  CONSTRAINT `fk_trucada_incidencia1`
    FOREIGN KEY (`incidencia_id`)
    REFERENCES `mydb`.`incidencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`provincia` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comarca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comarca` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `provincia_id` INT NOT NULL,
  PRIMARY KEY (`id`, `provincia_id`),
  INDEX `fk_comarca_provincia_idx` (`provincia_id` ASC) VISIBLE,
  CONSTRAINT `fk_comarca_provincia`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `mydb`.`provincia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`municipi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`municipi` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `comarca_id` INT NOT NULL,
  PRIMARY KEY (`id`, `comarca_id`),
  INDEX `fk_municipi_comarca1_idx` (`comarca_id` ASC) VISIBLE,
  CONSTRAINT `fk_municipi_comarca1`
    FOREIGN KEY (`comarca_id`)
    REFERENCES `mydb`.`comarca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`afectat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`afectat` (
  `id` INT NOT NULL,
  `CIP` VARCHAR(45) NULL,
  `comprovacio_CIP` TINYINT NULL,
  `telefon` VARCHAR(45) NULL,
  `comprovacio_Telefon` TINYINT NULL,
  `edat` INT NULL,
  `sexe` VARCHAR(45) NULL,
  `noms` VARCHAR(70) NULL,
  `cognoms` VARCHAR(70) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipus_recurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipus_recurs` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recurs_mobil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recurs_mobil` (
  `id` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  `tipus_recurs_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipus_recurs_id`),
  INDEX `fk_recurs_mobil_tipus_recurs1_idx` (`tipus_recurs_id` ASC) VISIBLE,
  CONSTRAINT `fk_recurs_mobil_tipus_recurs1`
    FOREIGN KEY (`tipus_recurs_id`)
    REFERENCES `mydb`.`tipus_recurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`incidencia_has_municipi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`incidencia_has_municipi` (
  `incidencia_id` INT NOT NULL,
  `municipi_id` INT NOT NULL,
  PRIMARY KEY (`incidencia_id`, `municipi_id`),
  INDEX `fk_incidencia_has_municipi_municipi1_idx` (`municipi_id` ASC) VISIBLE,
  INDEX `fk_incidencia_has_municipi_incidencia1_idx` (`incidencia_id` ASC) VISIBLE,
  CONSTRAINT `fk_incidencia_has_municipi_incidencia1`
    FOREIGN KEY (`incidencia_id`)
    REFERENCES `mydb`.`incidencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incidencia_has_municipi_municipi1`
    FOREIGN KEY (`municipi_id`)
    REFERENCES `mydb`.`municipi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.` tipus_alertant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.` tipus_alertant` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuari` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `password` VARCHAR(200) NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`, `roles_id`),
  INDEX `fk_usuari_roles1_idx` (`roles_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuari_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alertant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alertant` (
  `id` INT NOT NULL,
  `telefon` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `adreca` VARCHAR(45) NULL,
  `municipi_id` INT NOT NULL,
  ` tipus_alertant_id` INT NOT NULL,
  PRIMARY KEY (`id`, `municipi_id`, ` tipus_alertant_id`),
  INDEX `fk_alertantHabitual_municipi1_idx` (`municipi_id` ASC) VISIBLE,
  INDEX `fk_alertant_ tipus_alertant1_idx` (` tipus_alertant_id` ASC) VISIBLE,
  CONSTRAINT `fk_alertantHabitual_municipi1`
    FOREIGN KEY (`municipi_id`)
    REFERENCES `mydb`.`municipi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alertant_ tipus_alertant1`
    FOREIGN KEY (` tipus_alertant_id`)
    REFERENCES `mydb`.` tipus_alertant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`afectat_has_incidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`afectat_has_incidencia` (
  `afectat_id` INT NOT NULL,
  `incidencia_id` INT NOT NULL,
  PRIMARY KEY (`afectat_id`, `incidencia_id`),
  INDEX `fk_afectat_has_incidencia_incidencia1_idx` (`incidencia_id` ASC) VISIBLE,
  INDEX `fk_afectat_has_incidencia_afectat1_idx` (`afectat_id` ASC) VISIBLE,
  CONSTRAINT `fk_afectat_has_incidencia_afectat1`
    FOREIGN KEY (`afectat_id`)
    REFERENCES `mydb`.`afectat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_afectat_has_incidencia_incidencia1`
    FOREIGN KEY (`incidencia_id`)
    REFERENCES `mydb`.`incidencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`incidencia_has_recurs_mobil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`incidencia_has_recurs_mobil` (
  `incidencia_id` INT NOT NULL,
  `recurs_mobil_id` INT NOT NULL,
  `recurs_mobil_tipus_recurs_id` INT NOT NULL,
  `prioritar` TINYINT NULL,
  `date` TIME NULL,
  PRIMARY KEY (`incidencia_id`, `recurs_mobil_id`, `recurs_mobil_tipus_recurs_id`),
  INDEX `fk_incidencia_has_recurs_mobil_recurs_mobil1_idx` (`recurs_mobil_id` ASC, `recurs_mobil_tipus_recurs_id` ASC) VISIBLE,
  INDEX `fk_incidencia_has_recurs_mobil_incidencia1_idx` (`incidencia_id` ASC) VISIBLE,
  CONSTRAINT `fk_incidencia_has_recurs_mobil_incidencia1`
    FOREIGN KEY (`incidencia_id`)
    REFERENCES `mydb`.`incidencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incidencia_has_recurs_mobil_recurs_mobil1`
    FOREIGN KEY (`recurs_mobil_id` , `recurs_mobil_tipus_recurs_id`)
    REFERENCES `mydb`.`recurs_mobil` (`id` , `tipus_recurs_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alertant_has_incidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alertant_has_incidencia` (
  `alertant_id` INT NOT NULL,
  `alertant_municipi_id` INT NOT NULL,
  `alertant_ tipus_alertant_id` INT NOT NULL,
  `incidencia_id` INT NOT NULL,
  PRIMARY KEY (`alertant_id`, `alertant_municipi_id`, `alertant_ tipus_alertant_id`, `incidencia_id`),
  INDEX `fk_alertant_has_incidencia_incidencia1_idx` (`incidencia_id` ASC) VISIBLE,
  INDEX `fk_alertant_has_incidencia_alertant1_idx` (`alertant_id` ASC, `alertant_municipi_id` ASC, `alertant_ tipus_alertant_id` ASC) VISIBLE,
  CONSTRAINT `fk_alertant_has_incidencia_alertant1`
    FOREIGN KEY (`alertant_id` , `alertant_municipi_id` , `alertant_ tipus_alertant_id`)
    REFERENCES `mydb`.`alertant` (`id` , `municipi_id` , ` tipus_alertant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alertant_has_incidencia_incidencia1`
    FOREIGN KEY (`incidencia_id`)
    REFERENCES `mydb`.`incidencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
